enum Message {
    SEND_PAGE_ID,
    GET_PAGE_ID,
    HISTORY_GET_PAGE_ID,

    SEND_PAGE_READY,
    GET_PAGE_TITLE,

    SEND_PAGE_LOAD_COMPLETED,
    GET_PAGE_SCREENSHOT_OVERRIDE,
    SEND_PAGE_SCREENSHOT_OVERRIDE_ACK
}

export default Message;